Game Arena/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web.Mvc;
using Game_Arena.Models;
using Game_Arena.ViewModels;
using System.Data.Entity;
using System.Runtime.Caching;
using System.Web.Security;
using System.Web.SessionState;
namespace Game_Arena.Controllers
{
    public class CustomerController : Controller
    {
        //for accessing the database
        private ApplicationDbContext _context;

        public CustomerController()
        {
            //initialization
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        
        public ActionResult New()
        {
            var membershipTypes = _context.MembershipTypes.ToList();
            var viewModel = new CustomerFormViewModel
            {
                MembershipTypes = membershipTypes,
                Customer = new Customer()
            };
            return View("CustomerForm", viewModel);
        }

        //Gets called only by Http post and not by get
        
        public ActionResult Save(Customer customer)
        {
            //Checks for validation of the applied annotations
            if(!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                };
                return View("CustomerForm", viewModel); // returns the same form if not valid. 
               
            }
            if (customer.Id == 0)
            {
                //Its a new customer and has to be added.
                _context.Customers.Add(customer);

            }
            else
            {
                var customerInDb = _context.Customers.Single(c => c.Id == customer.Id);
                customerInDb.Name = customer.Name;
                customerInDb.MembershipTypeId = customer.MembershipTypeId;

                // above four lines OR Mapper.Map(customer, customerInDb)
            }
            _context.SaveChanges();
            ViewBag.Message = customer.Name + " successfully registered.";
            //return RedirectToAction("Index", "Customer");
            return RedirectToAction("Index","Home");
        }
        // GET: Customer
        public ActionResult Index()
        {
            if(Session["Email"] != null && Session["Email"].ToString()=="admin@gamearena.com")
            {
                return View("List");
            }

            else
            {
                return View("ReadOnlyList");
            }
        }

        public ActionResult Details(int id)
        {
            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }

      /*  public ActionResult Edit(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            else
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                };
                return View("CustomerForm", viewModel); //override otherwise it will look for a view named Edit which will lead to an exception.
            }
        }
        */
        public ActionResult LoginCustomer()
        {
            return View("Login");
        }


        [HttpPost]
        public ActionResult Login(Customer customer)
        {
            var userInfo = _context.Customers.Single(u => u.Email == customer.Email && u.Password == customer.Password);
            if(userInfo != null)
            {
                var userEmail = customer.Email;
                Session["Id"] = userInfo.Id;
                Session["Email"] = customer.Email;
                Session["Name"] = userInfo.Name;
                return RedirectToAction("LoggedIn");
            }
            else
            {
                ModelState.AddModelError("", "Username or Password is incorrect.");

            }

            return View("Login");
        }

        public ActionResult LoggedIn()
        {
            
            if(Session["Id"] != null)
            {
                return RedirectToAction("Index","Home");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session["Id"] = null;
            Session["Email"] = null;
            Session["Name"] = null;
            return RedirectToAction("Index", "Home");
        }


    }
}

Game Arena/Controllers/RentedGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Game_Arena.Controllers
{
    public class RentedGamesController : Controller
    {
        // GET: RentedGames
        public ActionResult New()
        {
            if (Session["Id"] != null)
            {
                return View();

            }
            else
            {
                return RedirectToAction("LoginCustomer", "Customer");
            }
        }

        public ActionResult List()
        {
            if(Session["Id"]!=null)
            {
                if (Session["Email"].ToString() == "admin@gamearena.com")
                {
                    return View("List");
                }
                else
                {
                    return RedirectToAction("LoginCustomer", "Customer");

                }
            }

            else
            {
                return RedirectToAction("LoginCustomer", "Customer");

            }
        }
    }
}

Game Arena/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Game Arena</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar");
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Game Arena by Hamza Mustafa Khan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Game Arena/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top navbar-expand-sm">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Game Arena", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (Session["Email"] != null && Session["Email"].ToString() == "admin@gamearena.com")
                {
                    <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                    <li>@Html.ActionLink("View Rentals","List","RentedGames")</li>
                }
                <li>@Html.ActionLink("New Rental", "New", "RentedGames")</li>
                <li>@Html.ActionLink("Games", "Index", "Games")</li>
            </ul>
            @Html.Partial("_LoginPartial")

        </div>
    </div>
</div>